upload:
  filepath: \\filebase\\QRCode
  baseurl: http://192.168.0.196:8090/filebase/QRCode
filebase:
  filepath: \\filebase
  fileurl: http://192.168.0.196:8090/filebase
spring:
  http:
    multipart:
      max-file-size: 20mb
      max-request-size: 20mb
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
  datasource:
    url: jdbc:mysql://192.168.0.196:3306/food_street?characterEncoding=UTF-8
    username: root
    password: root
    driver-class-name: com.mysql.jdbc.Driver
    minIdle: 2
    maxAction: 20
    maxWaitMillis: 8000
  cache:
    type: redis
  redis:
    database: 8
    host: 192.168.0.196
    port: 6379
    timeout: 20000
    pool:
      max-active: 8
      min-idle: 0
      max-idle: 8
      max-wait: -1
QRCode:
    Texturl: http://fresh.hafu365.com/order/#/cm
