upload:
  filepath: E:\\filebase\QRCode
  baseurl: http://192.168.0.198:8090/filebase/QRCode
filebase:
  filepath: E:\\filebase
  fileurl: http://192.168.0.198:8090/filebase
spring:
  http:
    multipart:
      max-file-size: 20mb
      max-request-size: 20mb
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
  datasource:
    url: jdbc:mysql://localhost:3306/food_street?characterEncoding=UTF-8
    username: root
    password: root
    driver-class-name: com.mysql.jdbc.Driver
    minIdle: 2
    maxAction: 20
    maxWaitMillis: 8000
    dbcp2:
          default-auto-commit: false
  cache:
    type: redis
  redis:
    database: 6
    host: 127.0.0.1
    port: 6379
    timeout: 20000
    pool:
      max-active: 8
      min-idle: 0
      max-idle: 8
      max-wait: -1
aliyuncs:
   dysmsapi:
      product: Dysmsapi                    #产品名称:云通信短信API产品,开发者无需替换
      domain: dysmsapi.aliyuncs.com        #产品域名,开发者无需替换
      accessKeyId : LTAIzK1iKtG5yRsI       #开发者自己的AK
      accessKeySecret: 3gxgNSNOsqYZQwc2AFBxrqlEYcl0Hx    #开发者自己的AK
